src/screens/auth/Signup.jsx
This commit enhances the features of the Signup Button as mentioned in issue #3.
Also, the spinner is animated using the `animate-spin` class.
=> fix issue #3

index.html
I have added the meta description tag and attached a catchy message to it, and also I have added a meta keyword section mentioning the important target keywords required for the SEO.
=> Added meta tags for SEO optimisation.

src/hooks/comment/useCreateComment.jsx
It fixes #5 , now you cant add a post comment with empty content.
=> Fix post comment empty content

src/screens/groups/groupDetails/Members.jsx
It fixes #7 , add the member profile link, on group members view.
=> Add member profile link on group members view

src/components/profile/friends/FriendCard.jsx, src/screens/profile/friends/AllFriends.jsx
It fixes #4 , now the "unfriend" feature also shows up on the Profile > Friends screen Friend Card.
=> Add unfriend func to profile > friends screen friend card

src/screens/auth/Login.jsx
Fix for #2 .
Added the following Enhancement in login
=> feature: Enhanced login button( #2)

CONTRIBUTING.md, README.md, src/components/settings/SidebarMenus.jsx, src/router/index.jsx, src/screens/settings/DeleteAccount.jsx
I further made a minor typo correction in the read me
=> adding delete account tab to settings

src/screens/PostDetails.jsx, src/services/comment.service.js
=> feat: add delete functionality for post comments

index.html
Closes #36 [FEATURE] Add open graph image 
Used og meta tags to solve the issue. Changed code -  
`<meta property="og:title" content="Hydrogen" />`
`<meta property="og:image" content="https://iili.io/LZUdJf.md.png" />`
` <meta property="og:description" content="Hydrogen is a full-stack social media app loaded with features such as secure login authentication, adding and managing friend requests, sharing media with friends, messeging with friends and many more. Click on the link to dive into the world of hydrogen." />`
=> Fixed #36 [FEATURE] Add open graph image 

src/components/profile/ProfileInfo.jsx, src/screens/profile/index.jsx
This PR Closes #49. Screenshot has been attached. @harshmangalam
=> Add last seen in user profile #49 Completed

package.json, pnpm-lock.yaml, src/components/header/Search.jsx
Reverts harshmangalam/hydrogen-solidjs-client#63
=> Revert "Added-Debounce for Search Optimization"

src/components/posts/create/Feelings.jsx
Added more emojis to improve user experience and to give more option to user to express themselve.
=> added more feelings and emojis

src/screens/groups/Create.jsx
=> Implemented spinner in create button and disabled button

src/hooks/auth/useSignup.jsx, src/screens/auth/Signup.jsx
I created a new function called `handlePassword` to use for the `input` instead of the one you previously had `handleInput`.
=> Adding Better Password Validation

src/components/groups/GroupCard.jsx
fixes #67
Signed-off-by: chankruze <chankruze@gmail.com>
=> fix: show group admin name on group card

src/components/header/Search.jsx
Fixed Error in My Debounce Code IT was a minor error and Now the Search Debounce feature is working
please checkout this
Closes: #6
=> Debouncingcode

src/components/sidebars/MenuSidebars/index.jsx, src/router/index.jsx
Added about tab in the profile page
Added routes to show about details in /about
=> Feat : Added user details page #77

src/components/friends/FriendBtn.jsx, src/screens/friends/Suggestions.jsx
=> friends suggestion accessibility

src/components/popup/Popup.jsx, src/components/posts/PostCard/PostHeader.jsx, src/components/posts/PostCard/PostUserPopup.jsx
This PR is for the enchantment #91.
This screenshot shows the popup over the user's name. You can see that it's very limited in the information, as the BE doesn't return email nor the last logged in date and time. There is commented out code in the `PostUserPopup.jsx` file that can be modified once those data properties are there.
=> Postcard user popup

src/App.jsx, src/hooks/auth/useLogout.jsx, src/hooks/auth/useLogoutBroadcast.jsx
=> Used broadcastchannel to listen for logout event

src/components/posts/PostCard/DeletePost.jsx, src/components/posts/PostCard/index.jsx
=> Enhance image accessibility

src/screens/groups/Notifications.jsx
This PR fixes #50 
UI update screenshots
=> Fix notification avatar styling issue

src/components/profile/ProfileInfo.jsx, src/screens/profile/index.jsx
https://github.com/harshmangalam/hydrogen-solidjs-client/issues/48
=> Add joined date in profile page

src/components/bottomSheet/index.jsx, src/screens/groups/Notifications.jsx
https://github.com/harshmangalam/hydrogen-solidjs-client/issues/90
=> Enhance accessibility on Group Notifications page

src/components/profile/ProfileInfo.jsx, src/components/ui/dataDisplay/UserStatusAvatar.jsx, src/screens/profile/about/index.jsx, src/screens/profile/index.jsx
https://github.com/harshmangalam/hydrogen-solidjs-client/issues/60
=> Improve lighthouse accessibility of profile page

src/screens/posts/Create.jsx
https://github.com/harshmangalam/hydrogen-solidjs-client/issues/88
i think link issue is fixed in a previous pr
=> Enhance create post page accessibility

src/screens/profile/about/Contact.jsx, src/screens/profile/about/Overview.jsx
This PR is a solution to issue https://github.com/harshmangalam/hydrogen-solidjs-client/issues/89.
=> Profile/about - Overview and Contact added

src/components/posts/PostCard/PostHeader.jsx, src/components/posts/PostCard/PostLikesUsersModal.jsx, src/components/posts/PostCard/PostReaction.jsx
=> Add Accessibility for PostCard components

README.md
Hey re-added the pr , pls give me Hacktoberfest accepted label
=> Updated and Beautified Readme.md with actual Indexing to all topics.

src/components/friends/HomeFriendsList.jsx, src/components/posts/PostCard/DeletePost.jsx, src/components/posts/PostCard/PostComment.jsx, src/components/posts/PostCard/PostHeader.jsx, src/components/posts/PostCard/PostHeart.jsx, src/components/posts/PostCard/PostLikesUsersModal.jsx, src/components/posts/PostCard/PostTitle.jsx, src/components/sidebars/MenuSidebars/MenuLink.jsx, src/components/sidebars/MenuSidebars/index.jsx, src/components/ui/dataDisplay/UserStatusAvatar.jsx
- Added `aria-label` to buttons and navigation elements
=> Enhance page accessibility

package.json, src/components/ui/inputs/Button.jsx, src/screens/groups/Create.jsx, src/utils/index.js
- Add two new packages: `clx` and `tailwind-merge`
- New util function called `cn` that will help with talwind class name merging
- Updated the `Button` component to me more flexible to use
=> Enhance create group section

src/context/auth.jsx, src/context/messenger.jsx, src/context/notifications.jsx, src/directives/isInViewport.js, src/hooks/auth/useLogin.jsx, src/hooks/auth/useLogout.jsx, src/hooks/auth/useSignup.jsx, src/hooks/comment/useCreateComment.jsx, src/hooks/group/useEditGroup.jsx, src/hooks/group/useUploadPic.jsx, src/hooks/messenger/useMessenger.jsx, src/hooks/post/useCreatePost.jsx, src/hooks/post/usePost.jsx, src/hooks/profile/useEditProfile.jsx, src/hooks/profile/useUploadProfilePic.jsx, src/hooks/settings/useChangePassword.jsx, src/hooks/useCloudinary.jsx, src/hooks/useCreateGroup.jsx, src/hooks/useCreateGroupPost.jsx, src/hooks/useFriendRequest.jsx, src/hooks/useGeolocations.jsx, src/hooks/useGroups.jsx
**Description**
I have commented out a few of the console.log statements whilst outright removing most of the others. Also, I have changed the error handling which now uses console.error.  
**Related Issue** : #115
=> Remove console.log statements and use console.error for error logging
